#!/bin/bash -

#SBATCH --account env540
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --partition=gpu
#SBATCH --qos=normal
#SBATCH --gres=gpu:1
#SBATCH --time=01:00:00
# Load modules
module load gcc python
# Activate virtual environment or conda environment
source ~/.venv/bin/activate # Replace with your environment setup
# Run your Python script
python training2.py # Replace with your script name